AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.nikhil::spring-boot-serverless
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  SpringBootServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.nikhil.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SpringBootServerlessApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/posts'
    Export:
      Name: SpringBootServerlessApi
